### PR TITLE
Increment version to 0.4.14.

### LINKED ISSUE #53: New release?
Could we get a new release published that includes merged PR #52 ? Because `typing` is now always installed, users need to run `pip uninstall typing` to fix their environments after installing pyCEC. Thanks!

### PR DESCRIPTION
**Pull request by newAM**
Closes #53

### CODE REVIEW

**Review by konikvranik — APPROVED** [review]

**Comment by newAM** [comment]
@konikvranik would I be able to get maintainer access to the repository too?

I would like to close on some of the other open issues as well (e.g. #43, #54), and make releases once they are resolved.

**Comment by newAM** [comment]
The CI is blocking this one, but to maintain coherency (since a release was made) I am going to manually merge this.

I opened a PR to fix the CI here: #57

**Comment by newAM** [comment]
Ah, nevermind, there are some hooks in place to prevent this going through without the CI:
```
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 305 bytes | 305.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 3 of 4 required status checks are expected.
To github.com:konikvranik/pyCEC.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:konikvranik/pyCEC.git'
```

@konikvranik Are you able to do one of the following?

* increase my github access to temporarily modify the protected branches
* remove the branch protection temporarily
* merge this (and #57 to fix this for the future) yourself

**Comment by newAM** [comment]
Thanks @konikvranik !

**Comment by konikvranik** [comment]
@newAM thank you for your contributions :-)

**Pull request merged**
